version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
