version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # node_modules 폴더를 컨테이너 내에 생성
    restart: always
