import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.scss"
import Header from "@/components/header"
import Footer from "@/components/footer"

const inter = Roboto({
	subsets: ["vietnamese", "latin"],
	weight: ["400", "700"],
	variable: "--font-inter",
})

export const metadata: Metadata = {
	title: {
		default: "누구누구 블로그",
		template: "%s | 누구누구 블로그",
	},
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="kr" color="light">
			<body className={inter.className}>
				<Header />
				<main className="layout">{children}</main>
				<Footer />
			</body>
		</html>
	)
}
